[colors.bright]
black = "0x555555"
blue = "0xcaa9fa"
cyan = "0x8be9fd"
green = "0x50fa7b"
magenta = "0xff79c6"
red = "0xff5555"
white = "0xffffff"
yellow = "0xf1fa8c"

[colors.normal]
black = "0x000000"
blue = "0xbd93f9"
cyan = "0x8be9fd"
green = "0x50fa7b"
magenta = "0xff79c6"
red = "0xff5555"
white = "0xbbbbbb"
yellow = "0xf1fa8c"

[colors.primary]
background = "0x151515"
foreground = "0xe0d0b0"

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u0017"
key = "Back"
mods = "Control"

[window]
opacity = 0.9
