require("rishavmngo.core.options")
require("rishavmngo.core.lazy")
require("rishavmngo.core.autocmds")
require("rishavmngo.lsp.lspconfig")
require("rishavmngo.lsp.mason")
require("rishavmngo.core.keymaps")

-- require("rishavmngo.plugins.toggle_term")
-- require("rishavmngo.plugins.indent_blankline")
-- require("rishavmngo.plugins.telescope")
-- require("rishavmngo.plugins.treesitter")
-- require("rishavmngo.plugins.cmp")
-- require("rishavmngo.plugins.comment")
-- require("rishavmngo.plugins.autopairs")
-- require("rishavmngo.plugins.bufferline")
--require("rishavmngo/plugins")
-- require("rishavmngo.plugins.lfrun")
-- require("rishavmngo.plugins.colorize")
-- require("rishavmngo.plugins.neosolarized")
