require("rishavmngo.core.options")
require("rishavmngo.core.plugins")
require("rishavmngo.core.autocmds")
require("rishavmngo.lsp.lspconfig")
require("rishavmngo.lsp.mason")
require("rishavmngo.core.keymaps")
